### ISSUE TITLE
LuaRocks package is broken

### ISSUE THREAD

**Issue by agladysh** [asb/lua-xmlreader#1]
Ubuntu 10.10
LuaRocks 2.0.5

<pre>
$ sudo luarocks install lua-xmlreader
Installing http://luarocks.org/repositories/rocks/lua-xmlreader-0.1-1.src.rock...
Archive:  /tmp/luarocks_luarocks-rock-lua-xmlreader-0.1-1-1551/lua-xmlreader-0.1-1.src.rock
  inflating: lua-xmlreader-0.1-1.rockspec  
 extracting: lua-xmlreader-0.1.tar.gz  
Applying patch fix_makefile.patch...
successfully patched Makefile
Warning: variable CFLAGS was not passed in build_variables
Warning: unmatched variable LUA_DIR
gcc -I/include -I/usr/include/libxml2  -Wall -O2   -c -o xmlreader.o xmlreader.c
xmlreader.c:1: fatal error: lua.h: No such file or directory
compilation terminated.
make: *** [xmlreader.o] Error 1

Error: Build error: Failed building.
</pre>

**Comment by asb** [comment]
Thanks for the report. I'll get a new rockspec that uses the 'builtin' build type this weekend.

**Comment by agladysh** [comment]
Thanks.

BTW, just found that I've reported this issue earlier: http://lists.luaforge.net/pipermail/luarocks-developers/2010-January/001422.html

**Comment by asb** [comment]
Hisham uploaded the submitted rockspec. The issue should be fixed with the lua-xmlreader-0.1-2.rockspec.

Thanks for the report!

**Comment by agladysh** [comment]
Fix confirmed, thanks!

On Tue, Aug 30, 2011 at 16:04, asb
reply@reply.github.com
wrote:
